#!/usr/bin/env node
/*
 * build.js — Neon Striker bundle builder
 * ----------------------------------------------------------------------
 * Concatenates the gameplay scripts (in their index.html load order) into
 * a single `game.bundle.js` wrapped in one IIFE.
 *
 * WHY: when the scripts load as separate classic <script> tags they all
 * share the *global* lexical scope, so top-level `let scrapCredits`,
 * `let score`, etc. are directly reachable + mutable from the browser
 * DevTools console (e.g. typing `scrapCredits = 999999`). Wrapping every
 * file in one shared IIFE moves that state into a private function scope —
 * the names no longer resolve in the console, defeating the casual
 * "type one line to cheat" exploit. (This is a deterrent, not a wall:
 * a determined user can still use Sources-panel breakpoints / local
 * overrides. True anti-cheat requires server-authoritative scoring.)
 *
 * This is a PURE concatenation — no source files are modified, so the
 * bundle is semantically identical to loading the files separately
 * (same execution order ⇒ same TDZ / hoisting behavior). The only
 * cross-file dependencies that cross the IIFE boundary go through
 * explicit `window.X = ...` assignments (window.Achievements,
 * window.Stats) or the separate database.js ES module's window.*
 * exports — all of which survive the wrap.
 *
 * USAGE:
 *   node build.js           # write game.bundle.js
 *   node build.js --check   # exit 1 if game.bundle.js is stale (for CI)
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Load order MUST match the classic <script> tags in index.html.
// database.js is intentionally excluded — it is an ES module and stays a
// separate <script type="module"> so its Firebase config stays private.
const SOURCES = [
  'audio.js',
  'config.js',
  'entities.js',
  'render.js',
  'collisions.js',
  'achievements.js',
  'stats.js',
  'main.js',
  'ui.js',
];

const OUT_FILE = 'game.bundle.js';
const ROOT = __dirname;

function buildBundle() {
  const parts = [];
  parts.push('/* AUTO-GENERATED by build.js — DO NOT EDIT BY HAND.');
  parts.push(' * Edit the source files listed below, then run `node build.js`.');
  parts.push(' * Sources (in order): ' + SOURCES.join(', '));
  parts.push(' *');
  parts.push(' * All gameplay state lives inside this IIFE so it is not');
  parts.push(' * reachable from the DevTools console (anti-cheat deterrent).');
  parts.push(' */');
  parts.push('(function () {');
  parts.push('"use strict";');

  for (const file of SOURCES) {
    const abs = path.join(ROOT, file);
    if (!fs.existsSync(abs)) {
      throw new Error(`Missing source file: ${file}`);
    }
    const code = fs.readFileSync(abs, 'utf8');
    parts.push('');
    parts.push(`/* ===== ${file} ===== */`);
    parts.push(code);
  }

  parts.push('');
  parts.push('})();');
  // Normalise to LF + single trailing newline for deterministic output.
  return parts.join('\n').replace(/\r\n/g, '\n').replace(/\n*$/, '\n');
}

function main() {
  const checkMode = process.argv.includes('--check');
  const bundle = buildBundle();
  const outPath = path.join(ROOT, OUT_FILE);

  if (checkMode) {
    const existing = fs.existsSync(outPath)
      ? fs.readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n')
      : '';
    if (existing !== bundle) {
      console.error(
        `✗ ${OUT_FILE} is stale. Run \`node build.js\` and commit the result.`
      );
      process.exit(1);
    }
    console.log(`✓ ${OUT_FILE} is up to date.`);
    return;
  }

  fs.writeFileSync(outPath, bundle, 'utf8');
  const kb = (Buffer.byteLength(bundle, 'utf8') / 1024).toFixed(1);
  console.log(`✓ Wrote ${OUT_FILE} (${kb} KB) from ${SOURCES.length} sources.`);
}

main();
